# Dataset Concat: 방문자 수 & 체류시간 고려

In [13]:
# 라이브러리 호출
import os
import pandas as pd
import numpy as np

In [14]:
print(os.getcwd())

C:\Users\samsung\TIL\DS\project\miniPJ\01_pj\data

In [15]:
os.chdir('C:/Users/samsung/TIL/DS/project/miniPJ/01_pj/data/')

In [16]:
# 데이터 로드

# 1. 기존 concat data
df = pd.read_csv('./final/df_security_concat_5.csv', encoding='cp949')
df.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)
df

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state
0,강원도,강릉시,26334028.0,1699.0,12301.0,64.0,99994.0,0.0271,90.36,강원도 강릉시
1,강원도,고성군,11612683.0,422.0,99992.0,94.0,99994.0,0.0271,90.36,강원도 고성군
2,강원도,동해시,6798468.0,330.0,4555.0,184.0,99994.0,0.0271,90.36,강원도 동해시
3,강원도,삼척시,8614642.0,932.0,7813.0,46.0,99994.0,0.0271,90.36,강원도 삼척시
4,강원도,속초시,19495563.0,441.0,3118.0,99993.0,99994.0,0.0271,90.36,강원도 속초시
...,...,...,...,...,...,...,...,...,...,...
248,세종특별자치시,전동면,NaN,27.0,821.0,1.0,1919.0,0.0041,708.64,세종특별자치시 전동면
249,세종특별자치시,전의면,NaN,46.0,909.0,2.0,2077.0,0.0041,708.64,세종특별자치시 전의면
250,세종특별자치시,조치원읍,NaN,203.0,1200.0,5.0,455.0,0.0041,708.64,세종특별자치시 조치원읍
251,세종특별자치시,종촌동,NaN,19.0,99992.0,99993.0,38.0,0.0041,708.64,세종특별자치시 종촌동
252,세종특별자치시,한솔동,NaN,40.0,99992.0,99993.0,95.0,0.0041,708.64,세종특별자치시 한솔동

In [23]:
# 2. 체류시간 데이터
df2 = pd.read_csv('./rawdata/체류특성_concat_2.csv', encoding='cp949')
df2

    state city  mean_hours  mean_days
0     강원도  강릉시      324.40      1.620
1     강원도  고성군      375.20      1.560
2     강원도  동해시      287.00      1.700
3     강원도  삼척시      318.60      1.680
4     강원도  속초시      280.20      1.400
..    ...  ...         ...        ...
224  충청북도  제천시      324.80      1.600
225  충청북도  증평군      233.00      1.680
226  충청북도  진천군      258.00      1.700
227  충청북도  청주시      208.15      1.765
228  충청북도  충주시      296.80      1.640

[229 rows x 4 columns]

In [29]:
# 1. 우선 개별 df별 new_state length 확인
# len(df.new_state.unique())  # 253
# len(df2.new_state.unique())  # 250

# 2. new_state 차이 나는 것이 무엇일까?
len(df.state.unique())  # 17
len(df2.state.unique())  # 17

len(df.city.unique())  # 231
len(df2.city.unique())  # 207

207

In [76]:
df2['new_state'] = df2.state + ' ' + df2.city
df2

    state city  mean_hours  mean_days new_state
0     강원도  강릉시      324.40      1.620   강원도 강릉시
1     강원도  고성군      375.20      1.560   강원도 고성군
2     강원도  동해시      287.00      1.700   강원도 동해시
3     강원도  삼척시      318.60      1.680   강원도 삼척시
4     강원도  속초시      280.20      1.400   강원도 속초시
..    ...  ...         ...        ...       ...
224  충청북도  제천시      324.80      1.600  충청북도 제천시
225  충청북도  증평군      233.00      1.680  충청북도 증평군
226  충청북도  진천군      258.00      1.700  충청북도 진천군
227  충청북도  청주시      208.15      1.765  충청북도 청주시
228  충청북도  충주시      296.80      1.640  충청북도 충주시

[229 rows x 5 columns]

In [30]:
231-207  # 세종시로 판별

24

In [75]:
231 - 24

207

In [33]:
len(df.loc[df.state == '세종특별자치시'])

25

In [74]:
252-229+1

24

In [91]:
# 기존 data + 체류시간 data 합치기
df_copy = df.copy()
df_copy.loc[df_copy.state == '세종특별자치시'].head()

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state
149,세종특별자치시,세종특별자치시,18211355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,세종특별자치시,가람동,NaN,5.0,99992.0,99993.0,99994.0,0.0041,708.64,세종특별자치시 가람동
230,세종특별자치시,고운동,NaN,92.0,99992.0,1.0,178.0,0.0041,708.64,세종특별자치시 고운동
231,세종특별자치시,금남면,NaN,119.0,1380.0,2.0,2598.0,0.0041,708.64,세종특별자치시 금남면
232,세종특별자치시,나성동,NaN,38.0,99992.0,99993.0,99994.0,0.0041,708.64,세종특별자치시 나성동

In [92]:
# 세종특별자치시 city = 세종특별자치시 통일

# 이상치 -> nan 값으로 바꾸기
df_copy.loc[df_copy.cctv_cnt == 99991.0, 'cctv_cnt'] = np.nan
df_copy.loc[df_copy.sclight_cnt == 99992.0, 'sclight_cnt'] = np.nan
df_copy.loc[df_copy.smalight_cnt == 99993.0, 'smalight_cnt'] = np.nan
df_copy.loc[df_copy.strlamp_cnt == 99994.0, 'strlamp_cnt'] = np.nan


df_copy.loc[df_copy.state == '세종특별자치시', 'city'] = '세종특별자치시'
df_copy.loc[df_copy.state == '세종특별자치시']

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state
149,세종특별자치시,세종특별자치시,18211355.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,세종특별자치시,세종특별자치시,NaN,5.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 가람동
230,세종특별자치시,세종특별자치시,NaN,92.0,NaN,1.0,178.0,0.0041,708.64,세종특별자치시 고운동
231,세종특별자치시,세종특별자치시,NaN,119.0,1380.0,2.0,2598.0,0.0041,708.64,세종특별자치시 금남면
232,세종특별자치시,세종특별자치시,NaN,38.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 나성동
233,세종특별자치시,세종특별자치시,NaN,26.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 다정동
234,세종특별자치시,세종특별자치시,NaN,37.0,NaN,2.0,NaN,0.0041,708.64,세종특별자치시 대평동
235,세종특별자치시,세종특별자치시,NaN,40.0,NaN,NaN,160.0,0.0041,708.64,세종특별자치시 도담동
236,세종특별자치시,세종특별자치시,NaN,44.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 반곡동
237,세종특별자치시,세종특별자치시,NaN,41.0,NaN,NaN,242.0,0.0041,708.64,세종특별자치시 보람동
238,세종특별자치시,세종특별자치시,NaN,54.0,603.0,NaN,924.0,0.0041,708.64,세종특별자치시 부강면
239,세종특별자치시,세종특별자치시,NaN,31.0,NaN,NaN,161.0,0.0041,708.64,세종특별자치시 새롬동
240,세종특별자치시,세종특별자치시,NaN,32.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 소담동
241,세종특별자치시,세종특별자치시,NaN,27.0,411.0,NaN,548.0,0.0041,708.64,세종특별자치시 소정면
242,세종특별자치시,세종특별자치시,NaN,31.0,NaN,4.0,74.0,0.0041,708.64,세종특별자치시 아름동
243,세종특별자치시,세종특별자치시,NaN,82.0,NaN,1.0,NaN,0.0041,708.64,세종특별자치시 어진동
244,세종특별자치시,세종특별자치시,NaN,69.0,398.0,4.0,1461.0,0.0041,708.64,세종특별자치시 연기면
245,세종특별자치시,세종특별자치시,NaN,30.0,569.0,NaN,942.0,0.0041,708.64,세종특별자치시 연동면
246,세종특별자치시,세종특별자치시,NaN,43.0,805.0,1.0,1815.0,0.0041,708.64,세종특별자치시 연서면
247,세종특별자치시,세종특별자치시,NaN,42.0,933.0,NaN,1771.0,0.0041,708.64,세종특별자치시 장군면
248,세종특별자치시,세종특별자치시,NaN,27.0,821.0,1.0,1919.0,0.0041,708.64,세종특별자치시 전동면
249,세종특별자치시,세종특별자치시,NaN,46.0,909.0,2.0,2077.0,0.0041,708.64,세종특별자치시 전의면
250,세종특별자치시,세종특별자치시,NaN,203.0,1200.0,5.0,455.0,0.0041,708.64,세종특별자치시 조치원읍
251,세종특별자치시,세종특별자치시,NaN,19.0,NaN,NaN,38.0,0.0041,708.64,세종특별자치시 종촌동
252,세종특별자치시,세종특별자치시,NaN,40.0,NaN,NaN,95.0,0.0041,708.64,세종특별자치시 한솔동

In [93]:
df_copy.loc[df_copy.state == '세종특별자치시'].visit_cnt.sum()  # 18211355.0

df_copy.loc[df_copy.state == '세종특별자치시'].cctv_cnt.sum()  # 1218.0
df_copy.loc[df_copy.state == '세종특별자치시'].sclight_cnt.sum()  # 8029.0.0
df_copy.loc[df_copy.state == '세종특별자치시'].smalight_cnt.sum()  # 23.0
df_copy.loc[df_copy.state == '세종특별자치시'].strlamp_cnt.sum()  # 15458.0
df_copy.loc[df_copy.state == '세종특별자치시'].crime_rate.mean()  # 0.004100000000000001
df_copy.loc[df_copy.state == '세종특별자치시'].avg_pop_density.mean()  # 708.64

708.64

In [94]:
df_copy.loc[df_copy.visit_cnt == 18211355.0, 'cctv_cnt'] = df_copy.loc[df_copy.state == '세종특별자치시'].cctv_cnt.sum()
df_copy.loc[df_copy.visit_cnt == 18211355.0, 'sclight_cnt'] = df_copy.loc[df_copy.state == '세종특별자치시'].sclight_cnt.sum()
df_copy.loc[df_copy.visit_cnt == 18211355.0, 'smalight_cnt'] = df_copy.loc[df_copy.state == '세종특별자치시'].smalight_cnt.sum()
df_copy.loc[df_copy.visit_cnt == 18211355.0, 'crime_rate'] = df_copy.loc[df_copy.state == '세종특별자치시'].crime_rate.mean()
df_copy.loc[df_copy.visit_cnt == 18211355.0, 'avg_pop_density'] = df_copy.loc[df_copy.state == '세종특별자치시'].avg_pop_density.mean()
df_copy.loc[df_copy.visit_cnt == 18211355.0, 'strlamp_cnt'] = df_copy.loc[df_copy.state == '세종특별자치시'].strlamp_cnt.sum()

df_copy.loc[df_copy.state == '세종특별자치시']

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state
149,세종특별자치시,세종특별자치시,18211355.0,1218.0,8029.0,23.0,15458.0,0.0041,708.64,NaN
229,세종특별자치시,세종특별자치시,NaN,5.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 가람동
230,세종특별자치시,세종특별자치시,NaN,92.0,NaN,1.0,178.0,0.0041,708.64,세종특별자치시 고운동
231,세종특별자치시,세종특별자치시,NaN,119.0,1380.0,2.0,2598.0,0.0041,708.64,세종특별자치시 금남면
232,세종특별자치시,세종특별자치시,NaN,38.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 나성동
233,세종특별자치시,세종특별자치시,NaN,26.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 다정동
234,세종특별자치시,세종특별자치시,NaN,37.0,NaN,2.0,NaN,0.0041,708.64,세종특별자치시 대평동
235,세종특별자치시,세종특별자치시,NaN,40.0,NaN,NaN,160.0,0.0041,708.64,세종특별자치시 도담동
236,세종특별자치시,세종특별자치시,NaN,44.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 반곡동
237,세종특별자치시,세종특별자치시,NaN,41.0,NaN,NaN,242.0,0.0041,708.64,세종특별자치시 보람동
238,세종특별자치시,세종특별자치시,NaN,54.0,603.0,NaN,924.0,0.0041,708.64,세종특별자치시 부강면
239,세종특별자치시,세종특별자치시,NaN,31.0,NaN,NaN,161.0,0.0041,708.64,세종특별자치시 새롬동
240,세종특별자치시,세종특별자치시,NaN,32.0,NaN,NaN,NaN,0.0041,708.64,세종특별자치시 소담동
241,세종특별자치시,세종특별자치시,NaN,27.0,411.0,NaN,548.0,0.0041,708.64,세종특별자치시 소정면
242,세종특별자치시,세종특별자치시,NaN,31.0,NaN,4.0,74.0,0.0041,708.64,세종특별자치시 아름동
243,세종특별자치시,세종특별자치시,NaN,82.0,NaN,1.0,NaN,0.0041,708.64,세종특별자치시 어진동
244,세종특별자치시,세종특별자치시,NaN,69.0,398.0,4.0,1461.0,0.0041,708.64,세종특별자치시 연기면
245,세종특별자치시,세종특별자치시,NaN,30.0,569.0,NaN,942.0,0.0041,708.64,세종특별자치시 연동면
246,세종특별자치시,세종특별자치시,NaN,43.0,805.0,1.0,1815.0,0.0041,708.64,세종특별자치시 연서면
247,세종특별자치시,세종특별자치시,NaN,42.0,933.0,NaN,1771.0,0.0041,708.64,세종특별자치시 장군면
248,세종특별자치시,세종특별자치시,NaN,27.0,821.0,1.0,1919.0,0.0041,708.64,세종특별자치시 전동면
249,세종특별자치시,세종특별자치시,NaN,46.0,909.0,2.0,2077.0,0.0041,708.64,세종특별자치시 전의면
250,세종특별자치시,세종특별자치시,NaN,203.0,1200.0,5.0,455.0,0.0041,708.64,세종특별자치시 조치원읍
251,세종특별자치시,세종특별자치시,NaN,19.0,NaN,NaN,38.0,0.0041,708.64,세종특별자치시 종촌동
252,세종특별자치시,세종특별자치시,NaN,40.0,NaN,NaN,95.0,0.0041,708.64,세종특별자치시 한솔동

In [95]:
drop_idxs = list(range(229,253,1))
# drop_idxs
df_copy.drop(drop_idxs, axis=0, inplace=True)
df_copy.loc[df_copy.city == '세종특별자치시']  # 229 rows

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state
149,세종특별자치시,세종특별자치시,18211355.0,1218.0,8029.0,23.0,15458.0,0.0041,708.64,NaN

In [96]:
# 합치기
len(df_copy.new_state.unique())  # 229
len(df2.new_state.unique())  # 229

229

In [97]:
df2.drop(['state', 'city'], axis=1, inplace=True)
df2

KeyError: "['state', 'city'] not found in axis"

In [98]:
df2[df2.new_state.str.contains('세종')]

     mean_hours  mean_days        new_state
149       290.4        1.8  세종특별자치시 세종특별자치시

In [85]:
merge_df = pd.merge(df_copy, df2, on='new_state', how='outer')
merge_df

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state,mean_hours,mean_days
0,강원도,강릉시,26334028.0,1699.0,12301.0,64.0,NaN,0.0271,90.36,강원도 강릉시,324.40,1.620
1,강원도,고성군,11612683.0,422.0,NaN,94.0,NaN,0.0271,90.36,강원도 고성군,375.20,1.560
2,강원도,동해시,6798468.0,330.0,4555.0,184.0,NaN,0.0271,90.36,강원도 동해시,287.00,1.700
3,강원도,삼척시,8614642.0,932.0,7813.0,46.0,NaN,0.0271,90.36,강원도 삼척시,318.60,1.680
4,강원도,속초시,19495563.0,441.0,3118.0,NaN,NaN,0.0271,90.36,강원도 속초시,280.20,1.400
...,...,...,...,...,...,...,...,...,...,...,...,...
225,충청북도,증평군,2848031.0,910.0,3869.0,8.0,NaN,0.0299,219.20,충청북도 증평군,233.00,1.680
226,충청북도,진천군,8030068.0,692.0,2.0,NaN,121.0,0.0299,219.20,충청북도 진천군,258.00,1.700
227,충청북도,청주시,62425138.0,9.0,25432.0,NaN,NaN,0.0299,219.20,충청북도 청주시,208.15,1.765
228,충청북도,충주시,14797862.0,1578.0,10600.0,219.0,NaN,0.0299,219.20,충청북도 충주시,296.80,1.640
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,세종특별자치시 세종특별자치시,290.40,1.800

In [103]:
df_copy.iloc[149, -1] = '세종특별자치시 세종특별자치시'
df_copy[df_copy['new_state'].isin(['세종특별자치시 세종특별자치시'])]

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state
149,세종특별자치시,세종특별자치시,18211355.0,1218.0,8029.0,23.0,15458.0,0.0041,708.64,세종특별자치시 세종특별자치시

In [104]:
merge_df = pd.merge(df_copy, df2, on='new_state', how='outer')
merge_df

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state,mean_hours,mean_days
0,강원도,강릉시,26334028.0,1699.0,12301.0,64.0,NaN,0.0271,90.36,강원도 강릉시,324.40,1.620
1,강원도,고성군,11612683.0,422.0,NaN,94.0,NaN,0.0271,90.36,강원도 고성군,375.20,1.560
2,강원도,동해시,6798468.0,330.0,4555.0,184.0,NaN,0.0271,90.36,강원도 동해시,287.00,1.700
3,강원도,삼척시,8614642.0,932.0,7813.0,46.0,NaN,0.0271,90.36,강원도 삼척시,318.60,1.680
4,강원도,속초시,19495563.0,441.0,3118.0,NaN,NaN,0.0271,90.36,강원도 속초시,280.20,1.400
...,...,...,...,...,...,...,...,...,...,...,...,...
224,충청북도,제천시,12125010.0,979.0,9024.0,314.0,NaN,0.0299,219.20,충청북도 제천시,324.80,1.600
225,충청북도,증평군,2848031.0,910.0,3869.0,8.0,NaN,0.0299,219.20,충청북도 증평군,233.00,1.680
226,충청북도,진천군,8030068.0,692.0,2.0,NaN,121.0,0.0299,219.20,충청북도 진천군,258.00,1.700
227,충청북도,청주시,62425138.0,9.0,25432.0,NaN,NaN,0.0299,219.20,충청북도 청주시,208.15,1.765
228,충청북도,충주시,14797862.0,1578.0,10600.0,219.0,NaN,0.0299,219.20,충청북도 충주시,296.80,1.640

In [105]:
merge_df[merge_df['new_state'].isin(['세종특별자치시 세종특별자치시'])]

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,strlamp_cnt,crime_rate,avg_pop_density,new_state,mean_hours,mean_days
149,세종특별자치시,세종특별자치시,18211355.0,1218.0,8029.0,23.0,15458.0,0.0041,708.64,세종특별자치시 세종특별자치시,290.4,1.8

In [111]:
# 칼럼 순서 변경
merge_df.columns  
# ['state', 'city', 'visit_cnt', 'cctv_cnt', 'sclight_cnt', 'smalight_cnt', 'strlamp_cnt', 'crime_rate', 'avg_pop_density', 'new_state', 'mean_hours', 'mean_days']
merge_df = merge_df[['state', 'city', 'visit_cnt', 'cctv_cnt', 'sclight_cnt', 'smalight_cnt', 'strlamp_cnt', 'crime_rate', 'avg_pop_density', 'mean_hours', 'mean_days', 'new_state']]
merge_df.drop('strlamp_cnt', axis=1, inplace=True)
merge_df

,state,city,visit_cnt,cctv_cnt,sclight_cnt,smalight_cnt,crime_rate,avg_pop_density,mean_hours,mean_days,new_state
0,강원도,강릉시,26334028.0,1699.0,12301.0,64.0,0.0271,90.36,324.40,1.620,강원도 강릉시
1,강원도,고성군,11612683.0,422.0,NaN,94.0,0.0271,90.36,375.20,1.560,강원도 고성군
2,강원도,동해시,6798468.0,330.0,4555.0,184.0,0.0271,90.36,287.00,1.700,강원도 동해시
3,강원도,삼척시,8614642.0,932.0,7813.0,46.0,0.0271,90.36,318.60,1.680,강원도 삼척시
4,강원도,속초시,19495563.0,441.0,3118.0,NaN,0.0271,90.36,280.20,1.400,강원도 속초시
...,...,...,...,...,...,...,...,...,...,...,...
224,충청북도,제천시,12125010.0,979.0,9024.0,314.0,0.0299,219.20,324.80,1.600,충청북도 제천시
225,충청북도,증평군,2848031.0,910.0,3869.0,8.0,0.0299,219.20,233.00,1.680,충청북도 증평군
226,충청북도,진천군,8030068.0,692.0,2.0,NaN,0.0299,219.20,258.00,1.700,충청북도 진천군
227,충청북도,청주시,62425138.0,9.0,25432.0,NaN,0.0299,219.20,208.15,1.765,충청북도 청주시
228,충청북도,충주시,14797862.0,1578.0,10600.0,219.0,0.0299,219.20,296.80,1.640,충청북도 충주시

In [112]:
merge_df.to_csv('./final/df_security_concat_7.csv', encoding='cp949', index=False)

In [107]:
# end-of-file